apiVersion: v1
kind: Service
metadata:
  name: prueba-api-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: prueba-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000